# Минимальная конфигурация Filebeat для тестирования
setup.ilm.enabled: false
setup.template.enabled: true
setup.template.name: "applogs"
setup.template.pattern: "applogs-*"

setup.kibana:
  host: ${KIBANA_HOST}

# Простой input без сложной обработки
filebeat.inputs:
- type: filestream
  id: app-logs-simple
  enabled: true
  paths:
    - /app/logs/*.log
  fields:
    service: "fastapi-app"
    environment: "production"
  fields_under_root: true

# Оптимизированные процессоры - убираем ненужные поля
processors:
  # Удаляем служебные поля Filebeat для экономии места
  - drop_fields:
      fields: [
        "agent.ephemeral_id", "agent.id", "agent.name", "agent.type", "agent.version",
        "ecs.version", 
        "host.architecture", "host.containerized", "host.hostname", "host.id", 
        "host.mac", "host.name", "host.os", "host.geo",
        "input.type",
        "log.file.device_id", "log.file.fingerprint", "log.file.inode", "log.file.path",
        "log.offset"
      ]
      ignore_missing: true

# Простой вывод в Elasticsearch
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOSTS}"]
  index: "app-logs-index-000001"
  
  # Производительность
  bulk_max_size: 50
  worker: 1
  
  # Template настройки
  template.enabled: true
  template.name: "applogs"
  template.pattern: "applogs-*"

# Логирование
logging.level: info
logging.to_files: false
logging.to_stderr: true

# Производительность
queue.mem:
  events: 1024
  flush.min_events: 10
  flush.timeout: 1s